### PR TITLE
Day 8

### PR DESCRIPTION
**Pull request by ylruiz**
Add CSS to the Contact us form, used TailwindCSS utilities to generate the required CSS.

### CODE REVIEW

**Comment by krvajal** [comment]
Can you add a little description of what this PR is all about?

**Comment by krvajal** [comment]
Looks good so far. Can you post an screenshot of how it loos so I dont have to start the server

**Comment by ylruiz** [comment]
I post a screenshot on trello.

**Comment by krvajal** [comment]
Add it here please

**Comment by krvajal** [comment]
Ohh no, I meant, upload the screenshot here in the comments, not as part of the repo 😅

**Comment by ylruiz** [comment]
https://screenshots.firefox.com/KP6W2SkurKY2CI7x/localhost

**Comment by krvajal** [comment]
Just drop the file here please

**Comment by ylruiz** [comment]
Screenshot_2019-04-10 Web Server

**Comment by ylruiz** [comment]
Screenshot_2019-04-10 Web Server(1)

**Comment by krvajal** [comment]
thank youuuuuuuuu

**Comment by ylruiz** [comment]
You are welcome

**Pull request merged**
